### ISSUE TITLE
Credential should be scoped to a valid region. 

### ISSUE THREAD

**Issue by matchasong** [matchasong/JankenHockey#101]
Credential should be scoped to a valid region.

**Comment by matchasong** [comment]
https://docs.aws.amazon.com/ja_jp/opsworks/latest/userguide/common-issues.html

**Comment by matchasong** [comment]
```
[ERROR] AttributeError: 'dict' object has no attribute 'token'
Traceback (most recent call last):
  File "/var/task/send_message.py", line 133, in handler
    asyncio.run(async_main(tasks), debug=True)
  File "/var/lang/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/var/lang/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/var/lang/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
  File "/var/task/send_message.py", line 111, in async_main
    await asyncio.gather(*tasks)
  File "/var/task/send_message.py", line 103, in async_send_message
    await process_async_http_request(item['id'], post_data)
  File "/var/task/send_message.py", line 78, in process_async_http_request
    auth.add_auth(aws_request)
  File "/var/lang/lib/python3.12/site-packages/botocore/auth.py", line 423, in add_auth
    self._modify_request_before_signing(request)
  File "/var/lang/lib/python3.12/site-packages/botocore/auth.py", line 448, in _modify_request_before_signing
    if self.credentials.token:
    ```
