### ISSUE TITLE
ParamValidationError: Parameter validation failed: Missing required parameter in input: "Key"

### ISSUE THREAD

**Issue by matchasong** [matchasong/JankenHockey#50]
disconnect.pyで以下のエラー発生

[ERROR] ParamValidationError: Parameter validation failed:
Missing required parameter in input: "Key"
Unknown parameter in input: "Item", must be one of: TableName, Key, Expected, ConditionalOperator, ReturnValues, ReturnConsumedCapacity, ReturnItemCollectionMetrics, ConditionExpression, ExpressionAttributeNames, ExpressionAttributeValues, ReturnValuesOnConditionCheckFailure
Traceback (most recent call last):
  File "/var/task/disconnect.py", line 21, in handler
    result = connection_table.delete_item(Item={'id': connection_id})
  File "/var/lang/lib/python3.12/site-packages/boto3/resources/factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "/var/lang/lib/python3.12/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/lang/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lang/lib/python3.12/site-packages/botocore/client.py", line 974, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/var/lang/lib/python3.12/site-packages/botocore/client.py", line 1048, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/var/lang/lib/python3.12/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())

**Comment by matchasong** [comment]
dynamodbには下記のConnectionIdが登録済みであり、disconnect.pyが受け取ったパラメータでも入っていることを確認済み

```DEPUnfJStjMAcGQ=```

**Comment by matchasong** [comment]
https://boto3.amazonaws.com/v1/documentation/api/1.35.9/reference/services/dynamodb/client/delete_item.html
