### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by matchasong** [matchasong/JankenHockey#60]
2024-12-20T04:22:20.029Z
[ERROR] TypeError: 'dict' object is not callable
Traceback (most recent call last):
  File "/var/task/send_message.py", line 51, in handler
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/var/lang/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
  File "/var/task/send_message.py", line 25, in async_send_message
    await asyncio.to_thread(apigw_management.post_to_connection(ConnectionId=item['id'], Data=post_data))
  File "/var/lang/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/var/lang/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)

**Comment by matchasong** [comment]
エラー内容が変わった

[WARNING]	2024-12-20T08:11:55.080Z	f7d18124-86f9-4bdd-8eb9-967488c04c0c	Executing <Task pending name='Task-2' coro=<async_send_message() running at /var/task/send_message.py:25> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /var/lang/lib/python3.12/asyncio/futures.py:391, Task.task_wakeup()] created at /var/lang/lib/python3.12/asyncio/base_events.py:449> cb=[gather.<locals>._done_callback() at /var/lang/lib/python3.12/asyncio/tasks.py:767] created at /var/lang/lib/python3.12/asyncio/tasks.py:695> took 0.538 seconds
