### ISSUE TITLE
BasicAuth() tuple is required instead

### ISSUE THREAD

**Issue by matchasong** [matchasong/JankenHockey#95]
```
[ERROR] TypeError: BasicAuth() tuple is required instead
Traceback (most recent call last):
  File "/var/task/send_message.py", line 96, in handler
    asyncio.run(async_main(tasks), debug=True)
  File "/var/lang/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/var/lang/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/var/lang/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
  File "/var/task/send_message.py", line 74, in async_main
    await asyncio.gather(*tasks)
  File "/var/task/send_message.py", line 66, in async_send_message
    await process_async_http_request(item['id'], post_data)
  File "/var/task/send_message.py", line 55, in process_async_http_request
    async with session.post(post_url, json=data) as response:
  File "/var/task/aiohttp/client.py", line 1425, in __aenter__
    self._resp: _RetType = await self._coro
  File "/var/task/aiohttp/client.py", line 675, in _request
    req = self._request_class(
  File "/var/task/aiohttp/client_reqrep.py", line 355, in __init__
    self.update_auth(auth, trust_env)
  File "/var/task/aiohttp/client_reqrep.py", line 576, in update_auth
    raise TypeError("BasicAuth() tuple is required instead")
```

**Comment by matchasong** [comment]
aiohttp.ClientSession().postのところっぽい

**Comment by matchasong** [comment]
エラーが変わったので別立てする
